FROM mdelapenya/liferay-portal:7-ce-ga5-tomcat-hsql

COPY portal-ext.properties /usr/local/liferay-ce-portal-7.0-ga5/portal-ext.properties

# ADD deploy /usr/local/liferay-ce-portal-7.0-ga5/deploy
ADD osgi-configs /usr/local/liferay-ce-portal-7.0-ga5/osgi/configs